on:
  push:
    branches: [ main ]
name: Deploy website on push
jobs:
  web-deploy:
    name: Auto Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2

    - name: Rsync Deployments Action
    # You may pin to the exact commit or the version.
    # uses: Burnett01/rsync-deployments@796cf0d5e4b535745ce49d7429f77cf39e25ef39
    uses: Burnett01/rsync-deployments@7.0.1
    with:
      # The switches
      switches: -avzr --delete
      # The remote shell argument
      rsh: # optional, default is 
      # Enables support for legacy RSA host keys on OpenSSH 8.8+
      legacy_allow_rsa_hostkeys: # optional, default is false
      # The local path
      path: # optional, default is 
      # The remote path
      remote_path: /var/www/html/cloud-computing-19122024
      # The remote host
      remote_host: 34.87.110.47
      # The remote port
      remote_port: # optional, default is 22
      # The remote user
      remote_user: ValentinoRyo10
      # The remote key
      remote_key: ${{ secrets.DEPLOY_KEY_PRIVATE }}
      # The remote key passphrase
      remote_key_pass: # optional, default is 
          
